configuration_file_version: 1

debug: true

# Default values might be a bit crazy.. They are intended for testing. Change them.

# kick_thresholds field ignores non-numerical characters and only reads three numbers separated, 
#   non-numericals are there only to make configuration file more readable.
#   Use 0 as an amount of seconds when you don't want to kick people.

kick_thresholds:
  - When 81 to 500 players online kick after 60 seconds
  - When 51 to 80  players online kick after 120 seconds
  - When 2  to 50  players online kick after 240 seconds
  - When 1  to 1  players online kick after 3600 seconds  
  
bot_detector:
  # Once the TPS get below acceptable_TPS, the BotDetector starts culling potential lag causer.
  acceptable_TPS: 17.5
  # critical_TPS_Change is the minimal change in TPS that needs to happen after kicking a player, 
  #   so he is marked as someone causing lag and his name is logged.
  critical_TPS_Change: 0.4
  # kicking_frequency is how often a player gets kicked and the TPS change monitored afterwards 
  #   in ticks
  kicking_frequency: 900
  # Whether players get banned for a long time/ until the tick is high again
  long_bans: false
  # Length of long ban
  ban_length: 21600000
  # Max locations per player to store while measuring movement patterns
  max_locations: 5
  # Max suspects to consider per Detector round
  max_suspects: 10
  # Baseline movement (in MC blocks) to be considered for bot detection
  min_baseline: 512
  # Maximum scan rounds to "ignore" a player who was previously cleared as a lag source
  max_reprieve: 5
  # Scan radius in chunks around location, to check for lag causes
  scan_radius: 4
  # Configure the threshold and individual contribution of bound types
  bounds:
    relaxation_factor: 1.1
    threshold: 2.5
    contained: 1.5
    contained_exclude_y: 1.5
    volume_similar: 1.0
    surface_similar: 1.0
    nearly_contained: 0.75
    nearly_contained_exclude_y: 0.75

lag_scanner:
  # Length of time to cache individual chunk results
  cache_timeout: 9000
  # Summation threshold of entity and tile costs for lag flag
  lag_threshold: 500
  # Per tickable block cost 
  tick_block:
    BANNER: 1
    BEACON: 5
    BREWING_STAND: 1
    MOB_SPAWNER: 3
    DROPPER: 3
    JUKEBOX: 1
    NOTE_BLOCK: 1
    SIGN: 1
    HOPPER: 5
    DISPENSER: 3
    FURNACE: 3
    BURNING_FURNACE: 4
    CHEST: 1
    ACTIVATOR_RAIL: 1
    DETECTOR_RAIL: 1
    DAYLIGHT_DETECTOR: 1
    DAYLIGHT_DETECTOR_INVERTED: 1
    DIODE: 1
    DIODE_BLOCK_OFF: 1
    DIODE_BLOCK_ON: 1
    PISTON_BASE: 2
    PISTON_STICKY_BASE: 2
    PISTON_MOVING_PIECE: 5
    PISTON_EXTENSION: 4
    POWERED_RAIL: 1
    REDSTONE_COMPARATOR: 1
    REDSTONE_COMPARATOR_OFF: 1
    REDSTONE_COMPARATOR_ON: 1
    REDSTONE_LAMP_OFF: 1
    REDSTONE_LAMP_ON: 1
    REDSTONE_TORCH_OFF: 1
    REDSTONE_TORCH_ON: 1
    WALL_BANNER: 1
    WALL_SIGN: 1
    SIGN_POST: 1
  # Per tickable entity cost
  tick_entity:
    BAT: 1
    FALLING_BLOCK: 3
    DROPPED_ITEM: 1
    ARMOR_STAND: 1
    BOAT: 2
    CAVE_SPIDER: 1
    CHICKEN: 1
    COW: 1
    CREEPER: 1
    ENDERMAN: 2
    ENDERMITE: 1
    GHAST: 2
    GUARDIAN: 2
    HORSE: 1
    IRON_GOLEM: 2
    MAGMA_CUBE: 2
    MINECART: 1
    MINECART_CHEST: 1
    MINECART_FURNACE: 2
    MINECART_HOPPER: 5
    MINECART_TNT: 3
    MUSHROOM_COW: 1
    OCELOT: 1
    PAINTING: 1
    PIG: 1
    PIG_ZOMBIE: 1
    PRIMED_TNT: 3
    RABBIT: 1
    SHEEP: 1
    SILVERFISH: 2
    SKELETON: 2
    SLIME: 2
    SNOWMAN: 2
    SPIDER: 1
    SQUID: 1
    VILLAGER: 1
    WITCH: 2
    WITHER: 3
    WOLF: 1
    ZOMBIE: 1

# warnings field reads the first number, the rest is text to be sent to a player
warnings:
  - 1 §4AFK Plugin - You'll be kicked in 1 second
  - 2 §4AFK Plugin - You'll be kicked in 2 seconds
  - 3 §4AFK Plugin - You'll be kicked in 3 seconds
  - 4 §4AFK Plugin - You'll be kicked in 4 seconds
  - 5 §4AFK Plugin - You'll be kicked in 5 seconds
  - 10 §4AFK Plugin - You'll be kicked in 10 seconds
  - 60 §4AFK Plugin - You'll be kicked in 1 minute
  - 300 §4AFK Plugin - You'll be kicked in 5 minutes
  - 600 §4AFK Plugin - You'll be kicked in 10 minutes
  - 1800 §4AFK Plugin - You'll be kicked in 30 minutes
  - 3600 §4AFK Plugin - You'll be kicked in 1 hour
  
  
# Yay, rainbows! :)  
kick_message: §cYou §6were §ekicked §adue §9to in§5activity


# Various strings. 

Str0: "Pluging is not running"
Str1: "AFK Player Garbage Collector has been enabled"
Str2: "AFK Player Garbage Collector has been disabled"
Str3: "§a%d players online: kicking after %sof being AFK"
Str4: "§a%d-%d players online: kicking after %sof being AFK"
Str5: "New configuration accepted, plugin enabled"
Str6: "New configuration rejected, plugin disabled"
Str7: "Plugin disabled"
Str8: "List of %d most inactive players:"
Str9: "%s last interacted on the server %sago"
Str10: "Previously defined threshold getting redefined in %s"
Str11: "Configuration file error: %s"
Str12: "Configuration file incomplete - plugin doesn't know when to kick players when there are %d players online"
Str13: "Error: Inconsistency in number of players detected"
Str14: "%s kicked for being AFK for %s"
Str15: "AFKPGC version: %s, the plugin is %s"
Str16: "AFKPGC is alive"


# Add player Account IDs (UUID) here to exempt them from the AFK checks
immune_accounts: []
